services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./tiktuck-backend
      dockerfile: dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  default:
    external: false
