name: tiktuck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.6
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.0
  image: ^4.1.3
  image_picker: ^1.0.5
  image_picker_for_web: ^3.0.1
  marquee: ^2.2.3
  video_player: ^2.8.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "img/logo.webp"
flutter:
  uses-material-design: true
  assets:
    - img/
    - video/
